<?php
$users = [
            ['name' => 'Neville Marks', 'age' => 77],
            ['name' => 'Laurel Buckner', 'age' => 73],
            ['name' => 'Zia Bullock', 'age' => 25],
            ['name' => 'Ishmael Porter', 'age' => 55],
            ['name' => 'Denton Lee', 'age' => 31],
            ['name' => 'Ferdinand Donovan', 'age' => 68],
            ['name' => 'Chastity Mcgowan', 'age' => 85],
            ['name' => 'Hasad Page', 'age' => 42],
            ['name' => 'Thane Moon', 'age' => 68],
            ['name' => 'Neville Marks', 'age' => 77],
            ['name' => 'Laurel Buckner', 'age' => 73],
            ['name' => 'Zia Bullock', 'age' => 25],
            ['name' => 'Wanda Hines', 'age' => 80],
            ['name' => 'Addison Campbell', 'age' => 42],
            ['name' => 'Joshua Kane', 'age' => 76],
            ['name' => 'Mufutau Fitzgerald', 'age' => 24],
            ['name' => 'Isadora Durham', 'age' => 71],
            ['name' => 'Nomlanga Howard', 'age' => 31],
            ['name' => 'Brittany Mccall', 'age' => 34],
            ['name' => 'Eleanor Alston', 'age' => 20],
            ['name' => 'Lillith Herring', 'age' => 62],
            ['name' => 'Aileen Kemp', 'age' => 53],
            ['name' => 'Aurora Freeman', 'age' => 33],
            ['name' => 'David Schneider', 'age' => 85],
            ['name' => 'Alfonso Mcfarland', 'age' => 40],
            ['name' => 'Griffin Sears', 'age' => 74],
            ['name' => 'Samuel Holloway', 'age' => 85],
            ['name' => 'Alika Crawford', 'age' => 63],
            ['name' => 'Cyrus Roman', 'age' => 58],
            ['name' => 'Raven Olsen', 'age' => 85],
            ['name' => 'Sebastian Waters', 'age' => 27],
            ['name' => 'Hedwig Best', 'age' => 89],
            ['name' => 'Quamar Powers', 'age' => 83],
            ['name' => 'Wesley Cruz', 'age' => 54],
            ['name' => 'Maris Pope', 'age' => 21],
            ['name' => 'Porter Salinas', 'age' => 56],
            ['name' => 'Flavia Pickett', 'age' => 76],
            ['name' => 'Isadora Conner', 'age' => 90],
            ['name' => 'Ivory Bray', 'age' => 58],
            ['name' => 'Hiram Gaines', 'age' => 84],
            ['name' => 'Jack Hood', 'age' => 83],
            ['name' => 'Katelyn Rosario', 'age' => 27],
            ['name' => 'Adria Phelps', 'age' => 65],
            ['name' => 'Candice Garner', 'age' => 75],
            ['name' => 'Rigel Jackson', 'age' => 82],
            ['name' => 'Alexandra Hart', 'age' => 86],
            ['name' => 'Lane Pittman', 'age' => 42],
            ['name' => 'Desiree Hancock', 'age' => 50],
            ['name' => 'Hasad Joyner', 'age' => 67],
            ['name' => 'Xavier Pittman', 'age' => 42],
            ['name' => 'Allen Lane', 'age' => 53],
            ['name' => 'Charde Noble', 'age' => 68],
            ['name' => 'Macon Dale', 'age' => 89],
            ['name' => 'Azalia Haley', 'age' => 64],
            ['name' => 'Ciaran Castro', 'age' => 47],
            ['name' => 'Hadley Rios', 'age' => 44],
            ['name' => 'Erasmus House', 'age' => 66],
            ['name' => 'Chase Sexton', 'age' => 57],
            ['name' => 'Vera Perry', 'age' => 41],
            ['name' => 'Clinton Carson', 'age' => 81],
            ['name' => 'Helen Wood', 'age' => 30],
            ['name' => 'Nevada Rowe', 'age' => 67],
            ['name' => 'Yoko Edwards', 'age' => 51],
            ['name' => 'Fuller Dudley', 'age' => 47],
            ['name' => 'Kalia Mckinney', 'age' => 47],
            ['name' => 'Maryam Mcclain', 'age' => 62],
            ['name' => 'Jaime Moses', 'age' => 27],
            ['name' => 'Jesse Chase', 'age' => 70],
            ['name' => 'MacKensie Watts', 'age' => 72],
            ['name' => 'Ruth Paul', 'age' => 69],
            ['name' => 'Britanni Carr', 'age' => 39],
            ['name' => 'Blythe Salas', 'age' => 85],
            ['name' => 'Kalia Mckinney', 'age' => 43],
            ['name' => 'Scarlett Wagner', 'age' => 47],
            ['name' => 'Maryam Mcclain', 'age' => 56],
            ['name' => 'Martena Weaver', 'age' => 89],
            ['name' => 'Armand Reese', 'age' => 64],
            ['name' => 'Janna Dyer', 'age' => 47],
            ['name' => 'Lamar Cox', 'age' => 55],
            ['name' => 'Signe Pearson', 'age' => 56],
            ['name' => 'Yuli Fuller', 'age' => 28],
            ['name' => 'Ivor Mosley', 'age' => 54],
            ['name' => 'Melissa Berger', 'age' => 70],
            ['name' => 'Nathaniel Molina', 'age' => 73],
            ['name' => 'Malachi Montoya', 'age' => 25],
            ['name' => 'Wylie Ratliff', 'age' => 72],
            ['name' => 'Georgia Booth', 'age' => 81],
            ['name' => 'Odette Keller', 'age' => 88],
            ['name' => 'Alyssa Mclaughlin', 'age' => 37],
            ['name' => 'Byron York', 'age' => 81],
            ['name' => 'Ethan Harvey', 'age' => 39],
        ];
        foreach ($users as $data) {
            $age = $data['age'];
            if ($age >= 35 && $age <= 65) {
                echo $data['name'] . ' is ' . $age . ' years old<br>';
            }
        }
        
?>